server:
  port: 1116
  
spring:
  application:
    metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
  datasource:
    driver-class-name: org.apache.derby.jdbc.ClientDriver  #org.apache.derby.jdbc.EmbeddedDriver   #oracle.jdbc.OracleDriver
    url: jdbc:derby://localhost:1527/derbycholla;create=true #jdbc:derby:C:\siv\database\derby\derbychola    # jdbc:derby://localhost:1527/sample;create=true  #jdbc:derby:C:\siv\Database\derby\derbychola;create=trues
    username: cholla
    password: cholla
    connection-test-query: SELECT 1 FROM SYSIBM.SYSDUMMY1;
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


    